# Generated by Django 5.0.6 on 2024-10-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowanaApp', '0002_remove_userprofile_phone_userprofile_subscribed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
